<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\SecureGate.Contratos\SecureGate.Contratos.csproj" />
    <ProjectReference Include="..\..\src\SecureGate.Proteccion\SecureGate.Proteccion.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SecureGate</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SecureGate.Cliente\SecureGate.Cliente.csproj" />
  </ItemGroup>
</Project>